import Head from 'next/head'
import Main from '../component/Main'
import Contain from '../component/contain'
import Details from '../component/Details'
import AuthContext from '../component/AuthContext'
import { useContext } from 'react'
import Link from 'next/link'
import styles from "../styles/SignUp.module.css"

export default function Home() {
  const {user} = useContext(AuthContext);
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Contain>
        <Details />
        <Main>
        <div >
        <p> {!user ? <span><p>Welcome!</p><button><Link href="/login"><a className={styles.btn}>Log in</a></Link></button> or <button><Link href="/signup"><a className={styles.btn}>Sign up</a></Link></button> Now To Have Access!</span> : ""}</p>

      

        <h1>{user? `welcome ${user.username}`: ""}</h1>
      </div>
        </Main>
      </Contain>

      
    </div>
  )
}
